# Generated by Django 5.0.3 on 2024-03-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_realtor',
            new_name='is_admin',
        ),
    ]
